## Image Classifier Using Keras

In [1]:
from tensorflow import keras

fashaion_mnist = keras.datasets.fashion_mnist
(xtrain_full, ytrain_full), (xtest,ytest) = fashaion_mnist.load_data()

In [2]:
xtrain_full.shape

(60000, 28, 28)

In [3]:
xtrain_full.dtype

dtype('uint8')

In [4]:
xvalid, xtrain = xtrain_full[:5000] / 255.0, xtrain_full[5000:] / 255.0
yvalid, ytrain = ytrain_full[:5000], ytrain_full[5000:]

In [5]:
class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
                   "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

class_names[ytrain[0]]

'Coat'

In [6]:
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[28,28]))
model.add(keras.layers.Dense(300, activation='relu'))
model.add(keras.layers.Dense(100, activation='relu'))
model.add(keras.layers.Dense(10, activation='softmax'))

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 300)               235500    
_________________________________________________________________
dense_1 (Dense)              (None, 100)               30100     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.layers

In [9]:
model.layers[1].name

'dense'

In [10]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

In [11]:
history = model.fit(xtrain, ytrain, epochs=30, validation_data=(xvalid, yvalid))

Train on 55000 samples, validate on 5000 samples
Epoch 1/30
55000/55000 [==============================] - 9s 170us/sample - loss: 0.7161 - accuracy: 0.7632 - val_loss: 0.5405 - val_accuracy: 0.8118
Epoch 2/30
55000/55000 [==============================] - 8s 141us/sample - loss: 0.4933 - accuracy: 0.8274 - val_loss: 0.4428 - val_accuracy: 0.8518
Epoch 3/30
55000/55000 [==============================] - 8s 139us/sample - loss: 0.4475 - accuracy: 0.8421 - val_loss: 0.4214 - val_accuracy: 0.8590
Epoch 4/30
55000/55000 [==============================] - 8s 138us/sample - loss: 0.4195 - accuracy: 0.8518 - val_loss: 0.3969 - val_accuracy: 0.8654
Epoch 5/30
55000/55000 [==============================] - 8s 139us/sample - loss: 0.3973 - accuracy: 0.8603 - val_loss: 0.4004 - val_accuracy: 0.8626
Epoch 6/30
55000/55000 [==============================] - 8s 139us/sample - loss: 0.3819 - accuracy: 0.8647 - val_loss: 0.3723 - val_accuracy: 0.8686
Epoch 7/30
55000/55000 [===========================

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
pd.DataFrame(history.history).plot(figsize=(8,5))
plt.grid(True)
plt.gca().set_ylim(0,1)
plt.show();

<Figure size 800x500 with 1 Axes>

In [13]:
model.evaluate(xtest, ytest)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[73.6663457674589, 0.8309]

In [14]:
xnew = xtest[:3]
y_proba = model.predict(xnew)
y_proba.round(2)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [15]:
y_pred = model.predict_classes(xnew)
y_pred

array([9, 2, 1])

In [16]:
import numpy as np
np.array(class_names)[y_pred]

array(['Ankle boot', 'Pullover', 'Trouser'], dtype='<U11')

### Regression MLP Using Sequential API

In [17]:
from tensorflow import keras
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()

Xtrain_full,Xtest, ytrain_full, ytest = train_test_split(housing.data, housing.target)

Xtrain, Xvalid, ytrain, yvalid = train_test_split(Xtrain_full, ytrain_full)

In [18]:
scalar = StandardScaler()
Xtrain_scaled = scalar.fit_transform(Xtrain)
Xvalid_scaled = scalar.fit_transform(Xvalid)
Xtest_scaled = scalar.fit_transform(Xtest)

In [19]:
model = keras.models.Sequential([
    keras.layers.Dense(30, activation='relu', input_shape=Xtrain.shape[1:]),
    keras.layers.Dense(1)
])

In [20]:
model.compile(loss='mean_squared_error', optimizer='sgd')

history = model.fit(Xtrain, ytrain, epochs=20, validation_data=(Xvalid, yvalid))

Train on 11610 samples, validate on 3870 samples
Epoch 1/20
11610/11610 [==============================] - 2s 133us/sample - loss: 2566501059621769361336240701440.0000 - val_loss: 663421513554471795294208.0000
Epoch 2/20
11610/11610 [==============================] - 1s 70us/sample - loss: 46175530257322050846720.0000 - val_loss: 283087461919219776.0000
Epoch 3/20
11610/11610 [==============================] - 1s 83us/sample - loss: 19703481663884884.0000 - val_loss: 120795646952.1861
Epoch 4/20
11610/11610 [==============================] - 1s 71us/sample - loss: 8407634391.6800 - val_loss: 51527.5363
Epoch 5/20
11610/11610 [==============================] - 1s 82us/sample - loss: 3589.0948 - val_loss: 1.2876
Epoch 6/20
11610/11610 [==============================] - 1s 74us/sample - loss: 1.3396 - val_loss: 1.2839
Epoch 7/20
11610/11610 [==============================] - 1s 83us/sample - loss: 1.3384 - val_loss: 1.2898
Epoch 8/20
11610/11610 [==============================] - 1s 78us/

In [21]:
mse_test = model.evaluate(Xtest, ytest)

5160/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [22]:
Xnew = Xtest[:5]
y_pred = model.predict(Xnew)

In [23]:
y_pred

array([[2.0866733],
       [2.0866733],
       [2.0866733],
       [2.0866733],
       [2.0866733]], dtype=float32)

## Working with Functional API

In [37]:
import numpy as np
import tensorflow as tf
np.random.seed(42)
tf.random.set_seed(42)

In [35]:
input_ = keras.layers.Input(shape=Xtrain.shape[1:])
hidden1 = keras.layers.Dense(30, activation="relu")(input)
hidden2 = keras.layers.Dense(30, activation="relu")(hidden1)
concat = keras.layers.concatenate([input, hidden2])
output = keras.layers.Dense(1)(concat)
model = keras.models.Model(inputs=[input], outputs=[output])

In [40]:
X_new = Xtest[:3]

In [42]:
model.compile(loss="mean_squared_error", optimizer=keras.optimizers.SGD(lr=1e-3))
history = model.fit(Xtrain, ytrain, epochs=20,
                    validation_data=(Xvalid, yvalid))
mse_test = model.evaluate(Xtest, ytest)
y_pred = model.predict(X_new)

Train on 11610 samples, validate on 3870 samples
Epoch 1/20
11610/11610 [==============================] - 2s 137us/sample - loss: nan - val_loss: nan
Epoch 2/20
11610/11610 [==============================] - 1s 81us/sample - loss: nan - val_loss: nan
Epoch 3/20
11610/11610 [==============================] - 1s 90us/sample - loss: nan - val_loss: nan
Epoch 4/20
11610/11610 [==============================] - 1s 82us/sample - loss: nan - val_loss: nan
Epoch 5/20
11610/11610 [==============================] - 1s 92us/sample - loss: nan - val_loss: nan
Epoch 6/20
11610/11610 [==============================] - 1s 84us/sample - loss: nan - val_loss: nan
Epoch 7/20
11610/11610 [==============================] - 1s 116us/sample - loss: nan - val_loss: nan
Epoch 8/20
11610/11610 [==============================] - 1s 126us/sample - loss: nan - val_loss: nan
Epoch 9/20
11610/11610 [==============================] - 1s 95us/sample - loss: nan - val_loss: nan
Epoch 10/20
11610/11610 [==============

In [43]:
y_pred

array([[nan],
       [nan],
       [nan]], dtype=float32)

In [44]:
np.random.seed(42)
tf.random.set_seed(42)

### Dynamic Model Using Subclassing API

In [46]:
class WideAndDeep(keras.models.Model):
    def __init__(self, units=30, activation='relu', **kwargs):
        super().__init__(**kwargs)
        self.hidden1 = keras.layers.Dense(units, activation=activation)
        self.hidden2 = keras.layers.Dense(units, activation=activation)
        self.main_output = keras.layers.Dense(1)
        self.aux_output = keras.layers.Dense(1)
        
    def call(self, inputs):
        input_A, input_B = inputs
        hidden1 = self.hidden1(input_B)
        hidden2 = self.hidden2(hidden1)
        concat = keras.layers.concatenate([input_A, hidden2])
        main_output = self.main_output(concat)
        aux_output = self.aux_output(hidden2)
        return main_output, aux_output

In [47]:
model.save("keras_model.h5")

In [48]:
model = keras.models.load_model("keras_model.h5")

In [49]:
model.save_weights('keras_weights.cktp')

In [50]:
model.load_weights('keras_weights.cktp')

In [51]:
keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)