## Data Types in Numpy

In [1]:
import numpy as np

In [6]:
# integer array
x = np.array([2,5,2,6,7,8])
x

array([2, 5, 2, 6, 7, 8])

In [7]:
# declaring type
y = np.array([3.5,4.6,6,1.2], dtype='float32')
y

array([3.5, 4.6, 6. , 1.2], dtype=float32)

In [19]:
# multi-dimensional arrays
x = np.array([range(i,i+2) for i in [2,4,6]])
x

array([[2, 3],
       [4, 5],
       [6, 7]])

In [20]:
# arrays with zeros 
# lenght specified
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
# arrays filled with ones
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [24]:
# 3X5 array with values 2.14
np.full((3,5), 2.14)

array([[2.14, 2.14, 2.14, 2.14, 2.14],
       [2.14, 2.14, 2.14, 2.14, 2.14],
       [2.14, 2.14, 2.14, 2.14, 2.14]])

In [44]:
# array with linear sequence
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [28]:
# arrays with values evenly spaced
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [30]:
# uniformly distributed random values between 0 and 1
np.random.random((3,3))

array([[0.19912101, 0.78068194, 0.12445351],
       [0.51732098, 0.30791656, 0.74805838],
       [0.17971201, 0.07142742, 0.1549314 ]])

In [34]:
# normally distributed random values with mean 0 and std 1
np.random.normal(0,1,(3,3))

array([[ 0.37098321,  0.70703205, -0.01248701],
       [ 1.12808344, -0.89231783, -0.83486549],
       [-0.3016382 , -0.46059959, -0.22061954]])

In [40]:
# array of random integers in range 
np.random.randint(0,10,(3,3))

array([[9, 7, 8],
       [8, 5, 7],
       [7, 5, 9]])

In [41]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
# uninitialized array, values taken from the memory
np.empty(3)

array([1., 1., 1.])