## Attributes of Numpy Arrays

In [2]:
import numpy as np
np.random.seed(0)

In [4]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,3))
x3 = np.random.randint(10, size=(2,3,5))

In [5]:
x1

array([3, 2, 7, 2, 0, 0])

In [6]:
x2

array([[4, 5, 5],
       [6, 8, 4],
       [1, 4, 9]])

In [7]:
x3

array([[[8, 1, 1, 7, 9],
        [9, 3, 6, 7, 2],
        [0, 3, 5, 9, 4]],

       [[4, 6, 4, 4, 3],
        [4, 4, 8, 4, 3],
        [7, 5, 5, 0, 1]]])

In [10]:
print("Dimention: ", x3.ndim)
print("Shape: ", x3.shape)
print("Size: ", x3.size) # total size of array
print("Type: ", x3.dtype)
print("Item Size: ", x3.itemsize) # size of each element(in bytes)
print("Total Size(in Bytes): ", x3.nbytes)

('Dimention: ', 3)
('Shape: ', (2, 3, 5))
('Size: ', 30)
('Type: ', dtype('int64'))
('Item Size: ', 8)
('Total Size(in Bytes): ', 240)
