## Attributes of Numpy Arrays

In [2]:
import numpy as np
np.random.seed(0)

In [11]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,3))
x3 = np.random.randint(10, size=(2,3,5))

In [5]:
x1

array([3, 2, 7, 2, 0, 0])

In [6]:
x2

array([[4, 5, 5],
       [6, 8, 4],
       [1, 4, 9]])

In [7]:
x3

array([[[8, 1, 1, 7, 9],
        [9, 3, 6, 7, 2],
        [0, 3, 5, 9, 4]],

       [[4, 6, 4, 4, 3],
        [4, 4, 8, 4, 3],
        [7, 5, 5, 0, 1]]])

In [10]:
print("Dimention: ", x3.ndim)
print("Shape: ", x3.shape)
print("Size: ", x3.size) # total size of array
print("Type: ", x3.dtype)
print("Item Size: ", x3.itemsize) # size of each element(in bytes)
print("Total Size(in Bytes): ", x3.nbytes)

('Dimention: ', 3)
('Shape: ', (2, 3, 5))
('Size: ', 30)
('Type: ', dtype('int64'))
('Item Size: ', 8)
('Total Size(in Bytes): ', 240)


In [3]:
# One dimensional arrays
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x = np.arange(20)

In [6]:
x[:5]

array([0, 1, 2, 3, 4])

In [7]:
x[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
x[4:7] # middle sub array

array([4, 5, 6])

In [9]:
x[::2] # everyother element

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
x[::-1] # reverse array

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

## Multi-dimensional array


In [14]:
x2

array([[3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [16]:
x2[:3,:2]

array([[3, 5],
       [4, 7],
       [8, 8]])

In [17]:
x2[:,0]

array([3, 4, 8])

In [18]:
x2[0,:]

array([3, 5, 2])

In [23]:
x2_sub = x2[:2,:3]

In [24]:
x2_sub

array([[3, 5, 2],
       [4, 7, 6]])

In [25]:
x2_copy = x2[:2,:2].copy()

In [26]:
x2_copy

array([[3, 5],
       [4, 7]])

In [41]:
grid = np.arange(1,13).reshape(4,3)
grid

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
x = np.array([1,2,3,4])
x.reshape(1,4)

array([[1, 2, 3, 4]])

In [44]:
x[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [45]:
x[np.newaxis,:]

array([[1, 2, 3, 4]])

In [46]:
x.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [48]:
y = np.array([5,6,7,8])

z = np.concatenate([x,y])

In [49]:
z

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
z[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [59]:
grid = np.random.randint(1,10, size=(3,3))

In [60]:
grid

array([[7, 9, 5],
       [2, 5, 9],
       [2, 2, 8]])

In [61]:
grid2 = np.random.randint(1,10, size=(3,3))

In [62]:
grid2

array([[4, 7, 8],
       [3, 1, 4],
       [6, 5, 5]])

In [65]:
np.concatenate([grid,grid2],axis=0)

array([[7, 9, 5],
       [2, 5, 9],
       [2, 2, 8],
       [4, 7, 8],
       [3, 1, 4],
       [6, 5, 5]])

In [67]:
np.vstack([grid,grid2])

array([[7, 9, 5],
       [2, 5, 9],
       [2, 2, 8],
       [4, 7, 8],
       [3, 1, 4],
       [6, 5, 5]])

In [68]:
np.hstack([grid,grid2])

array([[7, 9, 5, 4, 7, 8],
       [2, 5, 9, 3, 1, 4],
       [2, 2, 8, 6, 5, 5]])

In [69]:
np.split(grid,[3,3])

[array([[7, 9, 5],
        [2, 5, 9],
        [2, 2, 8]]),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64)]

In [70]:
np.vsplit(grid,[2,2])

[array([[7, 9, 5],
        [2, 5, 9]]), array([], shape=(0, 3), dtype=int64), array([[2, 2, 8]])]

In [71]:
np.hsplit(grid,[2,2])

[array([[7, 9],
        [2, 5],
        [2, 2]]), array([], shape=(3, 0), dtype=int64), array([[5],
        [9],
        [8]])]